name: almaty_offline_map
description: "A professional offline map application for Almaty landmarks."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Навигация и карты
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # Офлайн кэширование (FMTC) и база данных
  flutter_map_tile_caching:  ^9.1.4
  path_provider: ^2.1.2
  
  # Управление состоянием (State Management)
  provider: ^6.1.2
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Если у тебя будут свои иконки или картинки, добавь их сюда:
  # assets:
  #   - assets/images/